services:
  cfipup2dns:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: docker.m.daocloud.io/library/debian:bookworm-slim
        APT_MIRROR: mirrors.aliyun.com
    container_name: cfipup2dns
    restart: unless-stopped
    ports:
      - "9527:9527"
    environment:
      TZ: Asia/Shanghai
      PORT: 9527
      PROJECT_DIR: /data/project
      CONFIG_FILE: /data/project/config.json
      GH_PROXY: https://gh-proxy.org/
      MCIS_TAG: v0.2.3
    volumes:
      - ./data:/data
